[WIP-3] Feature: Python pip packages

diff --git a/after-effects b/after-effects
--- a/after-effects
+++ b/after-effects
@@ -87,6 +87,7 @@ function _init_printf_variables()
     readonly            _eol="[      EOL      ]"
     readonly   _pip_python_2="[      PIP2     ]"
     readonly   _pip_python_3="[      PIP3     ]"
+    readonly   _dependencies="[  Dependencies ]"
     readonly _eol_date_zesty="January 13th, 2018"
     #readonly           _falg="[     Flag      ]"
 
@@ -1045,95 +1046,124 @@ function _install_pip_python()
   # Function to install python pip packages
   # This function reads from File ./data/pip.list contains list python packages to be installed system wide.
   # Arguments : Two
-  # ARG1 : pip list
+  # ARG1 : pip package list
   # ARG2 : 2 for python 2 and 
   #      : 3 for Python 3.
 
+  #Check args
+  if [ $# -lt 2 ] ||  [ $# -gt 2 ] ; then
+    _log_and_show "\n${BLUE}${_error} Not enough arguments. \n${-info} Usage: _check_and_install_pre_requisites <list.apt> <commands to check>${NC}\n" && \
+    _log_and_exit "Internal Function Error. Invalid number of Arguments: $#." "18";
+  fi;
+
   update_repos;
   #Install starts here
-  local pip_packages
+  local pip_dependency_list exit_status _disp_pip_ver pip_command dependency_packages pip_command_result
   local pip_list="${1}"
   local pip_ver="${2}"
-  local exit_status
-  _debug_log "Option: Install Python Packaes via PIP, Function name: _install_pip_pythons"
+  _debug_log "Option: Install Python Packaes via PIP, Function name: _install_pip_python"
   _debug_log "pip Version : ${pip_ver}, List File : ${pip_list}"
-  while IFS= read -r line
-    do
-      _log_and_show "${_pip_ver} packages from pip.list"
-       # shellcheck disable=SC2002
-       # just to print it in logs so ignore shellcheck
-       cat "$dir/$pip_list" 2>&1 | _add_timestamp_to_cat_logs
-       pip_packages=$(cat "$dir/$line")
-       if [[ -z "$pip_packages" ]] && _log_and_show "${_warn} ${pip_list} is empty!!" && continue;
-       # Check if simulate is true
-        if [ "$simulate_apt_install" == "true" ]; then
-          set_yellow;
-          _log_and_show "${_simulate} PIP does not support simulated installs. Not performing install."
-          set_default;
-        else
-          # shellcheck disable=SC2086
-          pip install -r "${pip_list}" | _add_timestamp_to_pip_logs
-        fi
-        exit_status=$?
-        if [ "$exit_status" -eq 0 ]; then
-          set_yellow
-         _log_and_show "${_pip_ver} Installed packages from ${pip_list}"
-        else
-          _log_and_show "${YELLOW}${_oh_no} Something went wrong while installing packages in $pip_list.${NC}"
-          set_blue;
-          _log_and_show "${_notice} Please see the log file for more details."
-        fi
+
+  # Check Python Version
+  case ${pip_ver} in
+              2 | 2.7 | python2 )         _disp_pip_ver="${_pip_python_2}"; pip_dependency_list="pip2.apt"; pip_command="pip";;
+        3 | 3.6 | 3.5 | python3 )         _disp_pip_ver="${_pip_python_3}"; pip_dependency_list="pip3.apt"; pip_command="pip3";;
+                              * )         _log_and_exit "Internal Function Error. Arguments for python version." "19";;
+  esac
+
+  # Check if `python-pip` is installed, if not install it
+  command -v "$pip_command" > /dev/null
+  pip_command_result=$?
+  if [ $pip_command_result -eq 1 ]; then
+      set_red
+      _log_and_show "${_warn} $dep is not installed!${NC}"
+      set_default
+      _log_and_show "${_installing} packages from list : $pip_dependency_list"
+      dependency_packages=$(cat "$dir/$pip_dependency_list")
+
+      # If Dependency list is empty exit the script
+      if [[ -z "$dependency_packages" ]]; then
+        set_red;
+        _log_and_exit "${_error} PIP dependency list: $pip_dependency_list is empty." "19";
+      fi
+
+      # Check if simulate flag is set
+      if [ "$simulate_apt_install" == "true" ]; then
+        set_yellow;
+        _log_and_show "${_simulate} No Dependencies will be installed!!"
         set_default;
-        unset pip_packages;
-    done < "$pip_list"
-
-}
-
-
-function _check_and_install_pre_requisites()
-{
-  # This function installs required packages by other modules
-  # Checks if a command is not available and then installs the related package
-  # These should be present in your base ubuntu instal. If not present then, this function
-  # will install them. 
-  # Accepts two agruments 
-  # ARG 1 : list file (in dat folder) with apt packages which are dependencies. (Use quote if ther are multiple packags)
-  # ARG 2 & later : Commands to check if a package is installed already.
-
-  local apt_deps="${1}" # apt dependencies
-  local command_to_check="${2}" # command to check
-  local dependency_check_failed_count=0;
-  _log_and_show "${_info} Checking dependencies..."
-  for dep in "${dependencies[@]}"
-  do
-   :
-   command -v "$dep" > /dev/null
-   dep_res=$?
-   if [ "$dep_res" -eq 1 ]; then
-     set_red
-     _log_and_show "${_error} $dep is not installed!${NC}"
-     set_default
-     dependency_check_failed_count=$((dependency_check_failed_count+1))
-   fi
-  done
-
-  if [ "$dependency_check_failed_count" -gt 0 ]; then
-    set_yellow
-    _log_and_show "${_error} One or more dependencies not installed. Check logs or above message."
-    _log_and_exit "${_error} Sorry! $SCRIPT cannot continue!" "1"
-    set_default
+        # shellcheck disable=SC2086
+        apt-get -y install -s $dependency_packages 2>&1 | _add_timestamp_to_apt_logs
+      else
+        # shellcheck disable=SC2086
+        apt-get -y install $dependency_packages 2>&1 | _add_timestamp_to_apt_logs
+      fi
+      exit_status=$?
+      
+      if [ "$exit_status" -eq 0 ]; then
+        set_yellow
+        _log_and_show "${_installed} packages in the list $pip_dependency_list."
+      else
+        set_yellow;
+        _log_and_show "${_oh_no} Something went wrong while installing dependencies."
+        _log_and_show "${error} Python packages cannot be installed without dependencies."
+        set_red;
+        _log_and_exit "${_notice} Please see the log file for more details." "23"
+      fi
+  else 
+    _log_and_show "{_info} Dependency already satisfied."
   fi
+  # reset exit status
+  exit_status=0
+
+
+  _log_and_show "${_pip_ver} Installing python packages from : ${pip_list}"
+  # shellcheck disable=SC2002
+  # just to print it in logs so ignore shellcheck
+  cat "$dir/$pip_list" 2>&1 | _add_timestamp_to_cat_logs
+  # Check if pip package list is empty
+  
+  if [[ -z "$pip_packages" ]]; then
+    set_yellow;
+    _log_and_show "${_error} Package lists file ${pip-list} is empty!";
+    set_default;
+  else
+    # I package list isn't empty proceed to install pip packages
+    # Check if simulate is true
+    if [ "$simulate_apt_install" == "true" ]; then
+      set_yellow;
+      _log_and_show "${_disp_pip_ver} PIP does not support simulated installs. Not performing install."
+      set_default;
+    else
+      pip install -r "${pip_list}" 2>&1 | _add_timestamp_to_pip_logs
+    fi
+    exit_status=$?
+    if [ "$exit_status" -eq 0 ]; then
+      set_yellow
+      _log_and_show "${_disp_pip_ver} Installed packages from ${pip_list}"
+    else
+        set_yellow;
+        _log_and_show "${_disp_pip_ver} Something went wrong while installing packages in $pip_list."
+        set_blue;
+        _log_and_show "${_notice} Please see the log file for more details."
+    fi
+  set_default;
 }
+
 
 
 function install_pip_packages_2()
 {
   # Install Python 2 packages
-  update_repos;
-  _install_pre_requisites
-
+  _install_pip_python "pip.list" "2"
 }
 
+
+function install_pip_packages_3()
+{
+  # Install Python 2 packages
+  _install_pip_python "pip3.list" "3"
+}
 
 function install_debs ()
 {
@@ -1272,9 +1302,9 @@ function _process_opts
                               ;;
     set_gsettings )           _show_confirmation_dialog_for_tasks "Apply Custom gsettings" "Gsettings mentioned in the file gsettings.list will be Applied. \n Proceed?" "$task"
                               ;;
-    install_pip_packages_2 )  _show_confirmation_dialog_for_tasks "Install Python2 packages" "Python packaes for Python 2 mentioned in pip.list will be installed via pip. If necessary python-pip packaes will be installed from apt. \n Proceed?" "$task"
+    install_pip_packages_2 )  _show_confirmation_dialog_for_tasks "Install Python2 packages" "Python packaes for Python 2 mentioned in pip.list will be installed via pip. If necessary python-pip package will be installed from apt. \n Proceed?" "$task"
                               ;;
-    install_pip_packages_3 )  _show_confirmation_dialog_for_tasks "Install Python3 packages" "Python packaes for Python 3 mentioned in pip3.list will be installed via pip. If necessary python-pip packaes will be installed from apt. \n Proceed?" "$task"
+    install_pip_packages_3 )  _show_confirmation_dialog_for_tasks "Install Python3 packages" "Python packaes for Python 3 mentioned in pip3.list will be installed via pip. If necessary python-pip package will be installed from apt. \n Proceed?" "$task"
                               ;;
     delete_log_file )         _debug_log "Delete log selected"
                               delete_log_file;
