Updated lists * Some tweaks * Simulate install is by default false now * command line argument (-s --simulate) to toggle simulate * if simulate is set app upgrade wont be performed

diff --git a/after-effects b/after-effects
--- a/after-effects
+++ b/after-effects
@@ -16,7 +16,7 @@
 
 # Version:2.0
 # Author: Prasad Tengse
-# Licence: MIT
+# Licence: GPLv3
 # Github Repository: https://github.com/tprasadtp/after-effects-ubuntu
 # Requirements - Bash v4.4 and above
 
@@ -82,8 +82,9 @@ function _init_script_variables()
   readonly codename_previous_release="zesty"
   code_name_fix_latest="$code_name_latest_release"
 
-  # Simulate apt-get install
-  simulate_apt_install="true"
+  # Simulate apt-get install by default its false
+  # can be set to true if an argument -s or --simulate is passed ehile running the script
+  simulate_apt_install="false"
 
   #================ Because I care about Beauty of Output Logs =================
   readonly         _adding="[     Adding    ]"
@@ -170,8 +171,10 @@ printf "\n$(tput setaf 3)It was nice helping you,\nHave a great time with this L
 
 function _script_exit_log()
 {
+
     _debug_log "Exiting Script"
     printf "\nFinished %s on %s.\nLast exit code was: %d\n" "$SCRIPT" "$(date)" "$?" >> "$log_file"
+    _goodbye_msg;
 }
 
 
@@ -406,7 +409,7 @@ function add_repositories()
   wget -q  https://dl.google.com/linux/linux_signing_key.pub -O linux_signing_key.pub >> $"log_file"
   _debug_log "Adding Google Key to Trusted Keys list"
   apt-key add linux_signing_key.pub >> "$log_file" 2>&1  || _log_and_show "Adding Trusted Keys for Google failed."
-  _log_and_show "${_adding} Google Chrome Repository\n"
+  _log_and_show "${_adding} Google Chrome Repository"
   echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > ${SOURCES_FILE_DIR}/google.list || _log_and_show "Adding Google Chrome Repository failed"
   _log_and_show "${_adding} Google Earth Repository"
   echo "deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main" > ${SOURCES_FILE_DIR}/google-earth.list || _log_and_show "Adding Google Chrome Repository failed"
@@ -526,9 +529,12 @@ function upgrade_apps()
   _line_fill;
   sleep 5
   _debug_log "${_upgrading} packages..."
-  apt-get -y upgrade | _add_timestamp_to_apt_logs >> "$log_file"
-  apt-get -y dist-upgrade | _add_timestamp_to_apt_logs >> "$log_file"
-  exit_status=$?
+  # only do upgrades if simulate is set to false
+  if [ "$simulate_apt_install" == "false" ]; then
+    apt-get -y upgrade | _add_timestamp_to_apt_logs >> "$log_file"
+    apt-get -y dist-upgrade | _add_timestamp_to_apt_logs >> "$log_file"
+    exit_status=$?
+  fi
   set_yellow;
   if [ "$exit_status" -eq 0 ]; then
     _log_and_show "${_upgraded} Successfully!"
@@ -642,7 +648,7 @@ function install_apps()
          # Check if simulate is true
          if [ "$simulate_apt_install" == "true" ]; then
            set_yellow;
-           _log_and_show "${_simulate} apt-get install. Nothing will be installed!!"
+           _log_and_show "${_simulate} No packages will be installed!!"
            set_default;
            # disable shellcheck for quoted variable as its an exception
            # quoting $packages leads to errors.
@@ -657,7 +663,7 @@ function install_apps()
            set_yellow
            _log_and_show "${_installed} packages in the list $line"
          else
-           _log_and_show "${_oh_no} Something went wrong while installing  packages in $line"
+           _log_and_show "${_oh_no} Something went wrong while installing packages in $line"
            set_blue;
            _log_and_show "${_notice} Please see the log file for more details."
        fi
@@ -693,17 +699,19 @@ function install_debs ()
            _log_and_show "${_installing} $deb_name"
            # Check if simulate is true
            if [ "$simulate_apt_install" == "true" ]; then
-             _log_and_show "${_simulate} deb packages install. Nothing will be installed!!"
+             set_yellow
+             _log_and_show "${_simulate} DEB file will not be installed!!"
+             set_default
              dpkg -i --dry-run "$deb_name" | _add_timestamp_to_dpkg_logs >> "$log_file" 2>&1
              _debug_log "$_installing missing packages"
              apt-get -y install -f >> "$log_file"
             else
-            dpkg -i "$deb_name" | _add_timestamp_to_dpkg_logs >> "$log_file" 2>&1
+              dpkg -i "$deb_name" | _add_timestamp_to_dpkg_logs >> "$log_file" 2>&1
            fi
 
             # shellcheck disable=SC2181
            if [ "$?" = "0" ]; then
-                _log_and_show "${_installed} $line successfully"
+                _log_and_show "${_installed} $deb_name successfully"
            else
                 _log_and_show "${_oh_no} Some error occured during downloading and installing $line."
                 $?="0"
@@ -785,8 +793,24 @@ function main()
     exit 100;
   fi
 
-  _init_script_variables;
-  _init_script_initialization;
+    _init_script_variables;
+    _init_script_initialization;
+
+  # Process command line arguments.
+  while [ "$1" != "" ]; do
+      case ${1} in
+          -s | --simulate )       simulate_apt_install=true;
+                                  set_yellow;
+                                  _log_and_show "${_simulate} is set to true";
+                                  set_default;
+                                  ;;
+          * )                     printf "\n${BLUE}Invalid argument(s)${NC}\n"
+                                  exit -1
+                                  ;;
+      esac
+    shift
+  done
+
   _fix_ubuntu_derivatives;
   _test_internet_connection;
   _test_conflicting_apps;
