Support install Anaconda and packages

diff --git a/after-effects b/after-effects
--- a/after-effects
+++ b/after-effects
@@ -76,6 +76,7 @@ function _init_printf_variables()
     readonly      _dpkg_logs="[    PKG-Logs   ]"
     readonly   _apt_key_logs="[  APT-Key-Logs ]"
     readonly       _pip_logs="[    PIP-Logs   ]"
+    readonly     _conda_logs="[   Conda-Logs  ]"
     readonly            _cfg="[    R-Config   ]"
     readonly         _rtasks="[    R-Tasks    ]"
     readonly             _ci="[      C-I      ]"
@@ -1023,6 +1024,9 @@ function _set_yaml_config()
     #ae_task_pip3="${config__tasks__pip3[0]}"
     _check_bool "ae_task_pip3" "${config__tasks__pip3[0]}"
 
+    #ae_task_conda="${config__tasks__pip3[0]}"
+    _check_bool "ae_task_conda" "${config__tasks__conda[0]}"
+
     # Binaries Install
     _check_bool "ae_task_bin" "${config__tasks__binaries[0]}"
 
@@ -1063,6 +1067,7 @@ function _set_yaml_config()
         printf "${_rtasks} %-20s | %-10s |\n" "Purge packages" "$ae_task_purge"
         printf "${_rtasks} %-20s | %-10s |\n" "Python 2 Modules" "$ae_task_pip2"
         printf "${_rtasks} %-20s | %-10s |\n" "Python 3 Modules" "$ae_task_pip3"
+        printf "${_rtasks} %-20s | %-10s |\n" "Conda Modules" "$ae_task_conda"
         printf "${_rtasks} %-20s | %-10s |\n" "Static Binaries" "$ae_task_bin"
         set_default;
         _line_fill;
@@ -1100,6 +1105,7 @@ function _set_yaml_config()
         printf "${_rtasks} %-20s | %-10s |\n" "Purge packages" "$ae_task_purge"
         printf "${_rtasks} %-20s | %-10s |\n" "Python 2 Modules" "$ae_task_pip2"
         printf "${_rtasks} %-20s | %-10s |\n" "Python 3 Modules" "$ae_task_pip3"
+        printf "${_rtasks} %-20s | %-10s |\n" "Conda Modules" "$ae_task_conda"
         printf "${_rtasks} %-20s | %-10s |\n" "Static Binaries" "$ae_task_bin"
         _line_fill;
         _line_fill;
@@ -1186,6 +1192,7 @@ function _set_yaml_config()
 
     declare -gar parsed_pip2_packages=("${config__install__python2_[@]}")
     declare -gar parsed_pip3_packages=("${config__install__python3_[@]}")
+    declare -gar parsed_conda_packages=("${config__install__conda_[@]}")
     declare -gar parsed_bin_packages=("${config__install__binaries_[@]}")
  fi
 
@@ -1254,6 +1261,7 @@ function _set_list_config()
     ae_task_debs="true"
     ae_task_pip2="true"
     ae_task_pip3="true"
+    ae_task_conda="true"
     ae_task_purge="true"
     ae_task_bin="true"
 
@@ -2358,6 +2366,103 @@ function install_pip_packages_3()
   _install_pip_python "3"
 }
 
+function install_conda_packages_3()
+{
+  # Install conda 3 packages
+  _install_conda_packages "3"
+}
+
+function _install_conda_packages()
+{
+  # Function to install conda packages
+  # This function reads from File ${dir}/data/conda.list contains list python packages to be install system wide.
+  # Arguments: Two
+  # ARG1 : conda package list
+  # ARG2 : 2 for Anaconda Python 2 version and
+  #      : 3 for Anaconda Python 3 version.
+
+  # Check args
+  if [ $# -lt 1 ] ||  [ $# -gt 1 ] ; then
+    set_yellow;
+    _log_and_show "${_error} Incorrect number of arguments.\
+     \n${_info} Usage: _install_conda_packages <version>\n" && \
+    _log_and_exit "Internal Function Error. Invalid number of Arguments: $#." "19";
+  fi;
+
+  set_default;
+  #Install starts here
+  local conda_command="conda"
+  local requirements_file="/tmp/ae/conda_requirements.txt"
+  local conda_packages=("${parsed_conda_packages[@]}")
+  local exit_status conda_loc
+  local conda_ver="${1}"
+  _debug_log "Option: Install Python packages via Conda, Function name: _install_conda_packages"
+  _debug_log "Anaconda Version : ${conda_ver}"
+
+  # Check if "conda" is installed, if not install it
+  if ! conda_loc="$(type -p "$conda_command")" || [[ -z $conda_loc ]]; then
+      _log_and_warn "${_info} $conda_command is not installed!${NC}"
+      set_default;
+
+      # proceed to install Anaconda
+      _log_and_show "${_installing} Anaconda"
+
+      if [ "$simulate_apt_install" == "true" ] && [ "$CI" != "true" ]; then
+        set_yellow;
+        _log_and_show "${_simulate} No Dependencies will be installed!!"
+        set_default;
+      else
+        cd ~
+        exec=Anaconda3-2018.12-Linux-x86_64.sh
+        wget https://repo.continuum.io/archive/$exec
+        bash $exec -b -p ~/anaconda
+        rm $exec
+        echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc
+        source .bashrc
+        conda update conda
+      fi
+  else
+    _log_and_show "${_info} Anaconda installation detected."
+  fi
+
+  # reset exit status & color
+  exit_status=0
+  set_default;
+
+  _log_and_show "${_installing} Installing conda packages"
+  _debug_log "Requirements file: ${requirements_file}"
+  rm -f ${requirements_file} || _log_and_exit "Failed to remove ${requirements_file}" "38"
+  printf "%s\n" "${conda_packages[@]}" > "${requirements_file}"
+
+  # Check if package list is empty
+  if [[ ${#conda_packages[@]} -eq 0 ]]; then
+    _log_and_warn "${_error} Package array is empty!";
+    return
+  else
+    # If package list isn't empty proceed to install conda packages
+    # Check if simulate is true & is not running on TRAVIS/CI.
+    if [ "$simulate_apt_install" == "true" ] && [ "$CI" != "true" ]; then
+      set_yellow;
+      _log_and_show "${_whoops} Conda does not support simulated installs. Not performing install."
+      set_default;
+    else
+      $conda_command install -c conda-forge -y "${requirements_file}" 2>&1 | _add_timestamp_to_logs "${_pip_logs}"
+    fi
+    exit_status=$?
+    if [[ $exit_status -eq 0 ]]; then
+      set_green
+      _log_and_show "${_installed} python - ${1} modules"
+    else
+      _log_and_warn "${_error} Something went wrong while installing packages in $pip_list."
+      _log_and_warn "${_notice} Please see the log file for more details."
+    fi
+    set_default
+  fi
+
+  set_default;
+
+  _line_fill >> "$log_file"
+}
 
 function install_debs ()
 {
@@ -2504,6 +2609,7 @@ function all_in_one()
   install_debs;
   install_pip_packages_2;
   install_pip_packages_3;
+  install_conda_packages_3;
   purge_not_required;
   install_binaries;
   _line_fill;
@@ -2536,6 +2642,7 @@ function _process_menu
       debs       'Install DEB packages' \
       pip2       'Install Python 2 packages via pip' \
       pip3       'Install Python 3 packages via pip3' \
+      conda      'Install Python packages via conda' \
       bin        'Download & Install Static Binaries' \
       repo_rst   'Reset Repositories for cleanup' \
       ppa_rst    'Purge PPAs' \
@@ -2600,6 +2707,11 @@ function _process_menu
                   "Install Python3 packages" \
                   "Python packaes for Python 3 listed in pip3.list will be installed via pip. If necessary python3-pip package will be installed from apt.\n\nProceed?" \
                   "install_pip_packages_3"
+                  ;;
+      conda)       _show_confirmation_dialog_for_tasks \
+                  "Install conda packages" \
+                  "Anaconda packages for listed in conda.list will be installed via conda. If necessary Anaconda package will be installed from apt.\n\nProceed?" \
+                  "install_conda_packages_3"
                   ;;
       bin)        _show_confirmation_dialog_for_tasks \
                   "Install Static Binaries" \
@@ -2888,6 +3000,7 @@ function main()
     _autopilot_check_task_flag_and_run "$ae_task_debs" "install_debs"
     _autopilot_check_task_flag_and_run "$ae_task_pip2" "install_pip_packages_2"
     _autopilot_check_task_flag_and_run "$ae_task_pip3" "install_pip_packages_3"
+    _autopilot_check_task_flag_and_run "$ae_task_conda" "install_conda_packages_3"
     _autopilot_check_task_flag_and_run "$ae_task_purge" "purge_not_required"
     _autopilot_check_task_flag_and_run "$ae_task_bin" "install_binaries"
   else
